"""Report Synthesis Agent — Agent 6 of the AlphaLens LangGraph pipeline.

Replaces: Publishing Editor
Role: Consume all outputs from Agents 1-5 and produce a structured, five-section
      equity research report.  Each section is generated by a separate Gemini call
      with a 4-second sleep between calls to respect the 15 RPM free-tier limit.
      A template fallback is used when Gemini is unavailable for any section.
"""

import json
import logging
import time
from datetime import datetime, timezone
from typing import Any

from google import genai
from google.genai import types

from src.config import GEMINI_MODEL, GOOGLE_API_KEY
from src.state import AlphaLensState

logger = logging.getLogger(__name__)

# ── Gemini client (module-level singleton) ─────────────────────────────────────

_gemini_client: genai.Client | None = None


def _get_gemini_client() -> genai.Client | None:
    """Return (or lazily create) the module-level Gemini client.

    Returns:
        A ``genai.Client`` instance, or ``None`` when ``GOOGLE_API_KEY`` is absent.
    """
    global _gemini_client
    if _gemini_client is None:
        if not GOOGLE_API_KEY:
            logger.warning("[ReportSynthesis] GOOGLE_API_KEY not set — Gemini unavailable")
            return None
        try:
            _gemini_client = genai.Client(api_key=GOOGLE_API_KEY)
        except Exception as exc:
            logger.error("[ReportSynthesis] Failed to create Gemini client: %s", exc)
    return _gemini_client


def _call_gemini(
    prompt: str,
    max_tokens: int = 512,
    max_retries: int = 3,
) -> str:
    """Call Gemini with exponential back-off on HTTP 429 (rate limit).

    Args:
        prompt: Full prompt string to send.
        max_tokens: Maximum output tokens for the response.
        max_retries: Number of attempts before giving up.

    Returns:
        Generated text string, or empty string on failure.
    """
    client = _get_gemini_client()
    if client is None:
        return ""

    for attempt in range(1, max_retries + 1):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=max_tokens,
                    temperature=0.3,
                ),
            )
            return response.text or ""
        except Exception as exc:
            err_str = str(exc).lower()
            is_rate_limit = "429" in err_str or "quota" in err_str or "rate" in err_str
            if is_rate_limit and attempt < max_retries:
                wait = 2 ** attempt  # 2, 4, 8 seconds
                logger.warning(
                    "[ReportSynthesis] Gemini 429 on attempt %d/%d — sleeping %ds",
                    attempt, max_retries, wait,
                )
                time.sleep(wait)
            else:
                logger.error(
                    "[ReportSynthesis] Gemini call failed (attempt %d/%d): %s",
                    attempt, max_retries, exc,
                )
                return ""
    return ""


# ── Citation helpers ───────────────────────────────────────────────────────────

_SECTION_FILTER_MAP: dict[str, list[str]] = {
    "executive_summary": [],  # any chunk
    "financial_health": [
        "Management's Discussion and Analysis",
        "Financial Statements",
        "Notes to Financial Statements",
    ],
    "risk_flags": ["Risk Factors"],
    "valuation": ["Management's Discussion and Analysis", "Financial Statements"],
    "verification_verdict": [],  # any chunk
}


def _pick_citations(
    rag_chunks: list[dict],
    section_key: str,
    max_count: int = 3,
) -> list[dict]:
    """Select the top ``max_count`` RAG chunks relevant to a report section.

    Filters by section_name if filters are defined for the section key, then
    returns the entries with the lowest ``rank`` values (highest relevance).

    Args:
        rag_chunks: All retrieved chunks from Agent 2.
        section_key: One of the five section keys (e.g., ``"risk_flags"``).
        max_count: Maximum number of citation dicts to return.

    Returns:
        List of citation dicts with keys: ``source_file``, ``section_name``,
        ``page_number``, ``chunk_index``.
    """
    filters = _SECTION_FILTER_MAP.get(section_key, [])

    if filters:
        candidates = [
            c for c in rag_chunks
            if c.get("metadata", {}).get("section_name", "") in filters
        ]
    else:
        candidates = list(rag_chunks)

    # Sort by rank ascending (lower rank = more relevant)
    candidates.sort(key=lambda c: c.get("rank", 999))

    citations: list[dict] = []
    for chunk in candidates[:max_count]:
        meta = chunk.get("metadata", {})
        citations.append(
            {
                "source_file": meta.get("source_file", ""),
                "section_name": meta.get("section_name", ""),
                "page_number": meta.get("page_number", ""),
                "chunk_index": meta.get("chunk_index", ""),
            }
        )
    return citations


# ── Section builders ───────────────────────────────────────────────────────────

_PROMPT_PREFIX = (
    "You are a professional equity research analyst writing a section of a research report.\n"
    "Ticker: {ticker} | Date: {today}\n\n"
    "{section_context}\n\n"
    "Write the \"{section_title}\" section in 150-300 words. Use markdown formatting.\n"
    "Be specific with numbers. Do not give investment advice — include disclaimer "
    "\"Not financial advice.\"\n"
    "Respond with the section content only, no headers."
)


def _fmt_float(val: Any, fmt: str = ".2f", suffix: str = "") -> str:
    """Format a float for prompt injection, returning 'N/A' when None.

    Args:
        val: Numeric value or None.
        fmt: Python format spec string.
        suffix: String appended after the formatted number (e.g., ``"%"``).

    Returns:
        Formatted string or ``"N/A"``.
    """
    if val is None:
        return "N/A"
    try:
        return f"{float(val):{fmt}}{suffix}"
    except (TypeError, ValueError):
        return "N/A"


def _fmt_millions(val: Any) -> str:
    """Format a raw dollar amount as millions with M suffix.

    Args:
        val: Raw numeric value (dollars) or None.

    Returns:
        Formatted string such as ``"$1,234.56M"`` or ``"N/A"``.
    """
    if val is None:
        return "N/A"
    try:
        return f"${float(val) / 1_000_000:,.2f}M"
    except (TypeError, ValueError):
        return "N/A"


# ── Section 1: Executive Summary ──────────────────────────────────────────────

def _build_executive_summary(
    state: AlphaLensState,
    rag_chunks: list[dict],
    today: str,
) -> dict:
    """Generate the Executive Summary section.

    Args:
        state: Full pipeline state.
        rag_chunks: Retrieved filing chunks from Agent 2.
        today: ISO date string for the report header.

    Returns:
        Section dict with keys: title, content, confidence, citations.
    """
    ticker = state.get("ticker", "")
    fd: dict = state.get("financial_data", {})
    verification: dict = state.get("verification", {})
    risk_flags: list[dict] = state.get("risk_flags", [])

    company_name = fd.get("company_name", ticker)
    sector = fd.get("sector", "N/A")
    price = _fmt_float(fd.get("price"), ".2f", "")
    market_cap = _fmt_millions(fd.get("market_cap"))
    pe_ratio = _fmt_float(fd.get("pe_ratio"), ".1f")

    high_risk_count = sum(
        1 for f in risk_flags if f.get("severity", "").upper() == "HIGH"
    )
    overall_confidence = verification.get("confidence_scores", {}).get("overall", "MEDIUM")
    verification_verdict = verification.get("verification_verdict", "No verification data available.")

    section_context = (
        f"Company: {company_name} | Sector: {sector}\n"
        f"Current Price: ${price} | Market Cap: {market_cap} | P/E: {pe_ratio}\n"
        f"Overall Confidence: {overall_confidence}\n"
        f"Risk Flags (HIGH severity): {high_risk_count}\n"
        f"Verification Verdict: {verification_verdict}\n\n"
        f"Write a 2-paragraph executive summary for {ticker} ({company_name}). "
        f"Include current price, market cap, P/E, sector, and overall investment thesis. "
        f"Highlight the {high_risk_count} high-severity risk flags identified. "
        f"Confidence: {overall_confidence}. Be concise and data-driven."
    )

    prompt = _PROMPT_PREFIX.format(
        ticker=ticker,
        today=today,
        section_context=section_context,
        section_title="Executive Summary",
    )

    content = _call_gemini(prompt, max_tokens=512)
    if not content:
        content = (
            f"**Executive Summary** — Analysis unavailable (LLM rate limit). "
            f"Key data: {ticker} ({company_name}), Price=${price}, "
            f"Market Cap={market_cap}, P/E={pe_ratio}, Sector={sector}, "
            f"High-severity risks={high_risk_count}."
        )

    return {
        "title": "Executive Summary",
        "content": content,
        "confidence": overall_confidence if overall_confidence in ("HIGH", "MEDIUM", "LOW") else "MEDIUM",
        "citations": _pick_citations(rag_chunks, "executive_summary"),
    }


# ── Section 2: Financial Health ────────────────────────────────────────────────

def _build_financial_health(
    state: AlphaLensState,
    rag_chunks: list[dict],
    today: str,
) -> dict:
    """Generate the Financial Health section.

    Args:
        state: Full pipeline state.
        rag_chunks: Retrieved filing chunks from Agent 2.
        today: ISO date string for the report header.

    Returns:
        Section dict with keys: title, content, confidence, citations.
    """
    ticker = state.get("ticker", "")
    fd: dict = state.get("financial_data", {})

    revenue = _fmt_millions(fd.get("revenue"))
    net_income = _fmt_millions(fd.get("net_income"))
    gross_margin = _fmt_float(fd.get("gross_margin"), ".1%")
    operating_margin = _fmt_float(fd.get("operating_margin"), ".1%")
    free_cash_flow = _fmt_millions(fd.get("free_cash_flow"))
    debt_to_equity = _fmt_float(fd.get("debt_to_equity"), ".2f")
    current_ratio = _fmt_float(fd.get("current_ratio"), ".2f")

    sources_status: dict = fd.get("sources_status", {})
    sources_note = ", ".join(
        f"{k}: {v}" for k, v in sources_status.items()
    ) or "N/A"

    section_context = (
        f"Revenue: {revenue} | Net Income: {net_income}\n"
        f"Gross Margin: {gross_margin} | Operating Margin: {operating_margin}\n"
        f"Free Cash Flow: {free_cash_flow}\n"
        f"Debt-to-Equity: {debt_to_equity} | Current Ratio: {current_ratio}\n"
        f"Data Sources Status: {sources_note}"
    )

    prompt = _PROMPT_PREFIX.format(
        ticker=ticker,
        today=today,
        section_context=section_context,
        section_title="Financial Health",
    )

    content = _call_gemini(prompt, max_tokens=512)
    if not content:
        content = (
            f"**Financial Health** — Analysis unavailable (LLM rate limit). "
            f"Key data: Revenue={revenue}, Net Income={net_income}, "
            f"Gross Margin={gross_margin}, FCF={free_cash_flow}, "
            f"D/E={debt_to_equity}, Current Ratio={current_ratio}."
        )

    return {
        "title": "Financial Health",
        "content": content,
        "confidence": "MEDIUM",
        "citations": _pick_citations(rag_chunks, "financial_health"),
    }


# ── Section 3: Risk Flags ──────────────────────────────────────────────────────

def _build_risk_flags(
    state: AlphaLensState,
    rag_chunks: list[dict],
    today: str,
) -> dict:
    """Generate the Risk Flags section.

    Args:
        state: Full pipeline state.
        rag_chunks: Retrieved filing chunks from Agent 2.
        today: ISO date string for the report header.

    Returns:
        Section dict with keys: title, content, confidence, citations.
    """
    ticker = state.get("ticker", "")
    risk_flags: list[dict] = state.get("risk_flags", [])

    if risk_flags:
        flags_text = "\n".join(
            f"- {f.get('flag_type', 'UNKNOWN')} [{f.get('severity', 'UNKNOWN')}]: "
            f"{f.get('description', '')}"
            for f in risk_flags
        )
    else:
        flags_text = "No risk flags identified."

    has_high = any(f.get("severity", "").upper() == "HIGH" for f in risk_flags)
    confidence = "HIGH" if has_high else "MEDIUM"

    section_context = (
        f"Risk flags identified ({len(risk_flags)} total):\n{flags_text}"
    )

    prompt = _PROMPT_PREFIX.format(
        ticker=ticker,
        today=today,
        section_context=section_context,
        section_title="Risk Flags",
    )

    content = _call_gemini(prompt, max_tokens=512)
    if not content:
        content = (
            f"**Risk Flags** — Analysis unavailable (LLM rate limit). "
            f"Key data: {len(risk_flags)} risk flags identified. "
            f"{flags_text}"
        )

    return {
        "title": "Risk Flags",
        "content": content,
        "confidence": confidence,
        "citations": _pick_citations(rag_chunks, "risk_flags"),
    }


# ── Section 4: Valuation ───────────────────────────────────────────────────────

def _build_valuation(
    state: AlphaLensState,
    rag_chunks: list[dict],
    today: str,
) -> dict:
    """Generate the Valuation section.

    Confidence is always MEDIUM per the architecture spec (DCF always medium).

    Args:
        state: Full pipeline state.
        rag_chunks: Retrieved filing chunks from Agent 2.
        today: ISO date string for the report header.

    Returns:
        Section dict with keys: title, content, confidence, citations.
    """
    ticker = state.get("ticker", "")
    fd: dict = state.get("financial_data", {})
    quant: dict = state.get("quant_results", {})

    # DCF
    dcf: dict = quant.get("dcf", {})
    dcf_bear = _fmt_float(dcf.get("bear"), ".2f")
    dcf_base = _fmt_float(dcf.get("base"), ".2f")
    dcf_bull = _fmt_float(dcf.get("bull"), ".2f")
    wacc = _fmt_float(dcf.get("wacc"), ".1%") if dcf.get("wacc") else "N/A"

    # Technicals
    technicals: dict = quant.get("technicals", {})
    rsi = _fmt_float(technicals.get("rsi"), ".1f")
    macd_signal = technicals.get("macd_signal", "N/A")

    # Earnings surprise
    earnings: dict = quant.get("earnings_surprise", {})
    surprise_pct = _fmt_float(earnings.get("surprise_pct"), ".1%") if earnings.get("surprise_pct") is not None else "N/A"

    # Ratios from financial data
    pe_ratio = _fmt_float(fd.get("pe_ratio"), ".1f")
    forward_pe = _fmt_float(fd.get("forward_pe"), ".1f")

    section_context = (
        f"DCF Range: Bear=${dcf_bear} / Base=${dcf_base} / Bull=${dcf_bull} | WACC: {wacc}\n"
        f"RSI (14-day): {rsi} | MACD Signal: {macd_signal}\n"
        f"Earnings Surprise: {surprise_pct}\n"
        f"Trailing P/E: {pe_ratio} | Forward P/E: {forward_pe}"
    )

    prompt = _PROMPT_PREFIX.format(
        ticker=ticker,
        today=today,
        section_context=section_context,
        section_title="Valuation",
    )

    content = _call_gemini(prompt, max_tokens=512)
    if not content:
        content = (
            f"**Valuation** — Analysis unavailable (LLM rate limit). "
            f"Key data: DCF Bear=${dcf_bear}/Base=${dcf_base}/Bull=${dcf_bull}, "
            f"WACC={wacc}, RSI={rsi}, MACD={macd_signal}, "
            f"EPS Surprise={surprise_pct}, P/E={pe_ratio}, Fwd P/E={forward_pe}."
        )

    return {
        "title": "Valuation",
        "content": content,
        "confidence": "MEDIUM",  # Always MEDIUM per architecture spec
        "citations": _pick_citations(rag_chunks, "valuation"),
    }


# ── Section 5: Verification Verdict ───────────────────────────────────────────

def _build_verification_verdict(
    state: AlphaLensState,
    rag_chunks: list[dict],
    today: str,
) -> dict:
    """Generate the Verification Verdict section.

    Args:
        state: Full pipeline state.
        rag_chunks: Retrieved filing chunks from Agent 2.
        today: ISO date string for the report header.

    Returns:
        Section dict with keys: title, content, confidence, citations.
    """
    ticker = state.get("ticker", "")
    verification: dict = state.get("verification", {})

    divergences: list[dict] = verification.get("divergences", [])
    confidence_scores: dict = verification.get("confidence_scores", {})
    overall_confidence = confidence_scores.get("overall", "MEDIUM")
    verification_verdict = verification.get("verification_verdict", "No verification data available.")
    llm_available: bool = verification.get("llm_available", True)

    if divergences:
        divergence_text = "\n".join(
            f"- Claim: \"{d.get('claim', '')}\" | "
            f"Actual: \"{d.get('actual_data', '')}\" | "
            f"Severity: {d.get('severity', 'UNKNOWN')}"
            for d in divergences[:5]  # cap at 5 for prompt length
        )
    else:
        divergence_text = "No divergences detected."

    scores_text = " | ".join(
        f"{k}: {v}" for k, v in confidence_scores.items()
    ) or "N/A"

    section_context = (
        f"Verification Verdict: {verification_verdict}\n"
        f"Confidence Scores: {scores_text}\n"
        f"LLM Available: {llm_available}\n"
        f"Divergences ({len(divergences)} total):\n{divergence_text}"
    )

    prompt = _PROMPT_PREFIX.format(
        ticker=ticker,
        today=today,
        section_context=section_context,
        section_title="Verification Verdict",
    )

    content = _call_gemini(prompt, max_tokens=512)
    if not content:
        content = (
            f"**Verification Verdict** — Analysis unavailable (LLM rate limit). "
            f"Key data: {verification_verdict} | Divergences: {len(divergences)} | "
            f"Scores: {scores_text}."
        )

    return {
        "title": "Verification Verdict",
        "content": content,
        "confidence": overall_confidence if overall_confidence in ("HIGH", "MEDIUM", "LOW") else "MEDIUM",
        "citations": _pick_citations(rag_chunks, "verification_verdict"),
    }


# ── Overall confidence rollup ──────────────────────────────────────────────────

_CONFIDENCE_RANK: dict[str, int] = {"HIGH": 3, "MEDIUM": 2, "LOW": 1}
_RANK_CONFIDENCE: dict[int, str] = {3: "HIGH", 2: "MEDIUM", 1: "LOW"}


def _rollup_confidence(sections: dict[str, dict]) -> str:
    """Compute the lowest confidence level across all report sections.

    Uses the minimum (most conservative) confidence of all five sections.

    Args:
        sections: Dict mapping section key → section dict with a ``confidence`` key.

    Returns:
        One of ``"HIGH"``, ``"MEDIUM"``, or ``"LOW"``.
    """
    ranks = [
        _CONFIDENCE_RANK.get(s.get("confidence", "MEDIUM"), 2)
        for s in sections.values()
    ]
    return _RANK_CONFIDENCE.get(min(ranks, default=2), "MEDIUM")


# ── Agent entry point ──────────────────────────────────────────────────────────

def report_synthesis_agent(state: AlphaLensState) -> dict:
    """Synthesize a structured five-section equity research report.

    Reads all previously computed state fields (financial_data, rag_chunks,
    quant_results, risk_flags, verification) and generates one markdown section
    per Gemini call.  A 4-second sleep is inserted between successive calls to
    remain within the Gemini free-tier 15 RPM rate limit.

    On any section failure the agent substitutes a template fallback so the
    pipeline always returns a structurally complete report dict.

    Args:
        state: Complete LangGraph pipeline state populated by Agents 1-5.

    Returns:
        Partial state dict with keys:
            ``report``: Structured report dict with five sections, overall
                confidence, and a legal disclaimer.
            ``metadata``: Merged dict with
                ``agent_latencies.report_synthesis`` (float, seconds).
        Never raises — all exceptions are caught and surfaced via fallback content.
    """
    t_start = time.monotonic()
    ticker: str = state.get("ticker", "UNKNOWN").upper().strip()
    rag_chunks: list[dict] = state.get("rag_chunks", [])
    today: str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    logger.info("[ReportSynthesis] Starting for ticker=%s", ticker)

    # Section builder registry — order matters for rate-limit sleeps
    section_builders: list[tuple[str, Any]] = [
        ("executive_summary", _build_executive_summary),
        ("financial_health", _build_financial_health),
        ("risk_flags", _build_risk_flags),
        ("valuation", _build_valuation),
        ("verification_verdict", _build_verification_verdict),
    ]

    sections: dict[str, dict] = {}

    for idx, (section_key, builder_fn) in enumerate(section_builders):
        logger.info(
            "[ReportSynthesis] Building section %d/5: %s", idx + 1, section_key
        )
        try:
            section_dict = builder_fn(state, rag_chunks, today)
        except Exception as exc:
            logger.error(
                "[ReportSynthesis] Section '%s' builder raised: %s", section_key, exc
            )
            section_dict = {
                "title": section_key.replace("_", " ").title(),
                "content": (
                    f"**{section_key.replace('_', ' ').title()}** — "
                    f"Section generation failed unexpectedly."
                ),
                "confidence": "LOW",
                "citations": [],
            }

        sections[section_key] = section_dict

        # Sleep between Gemini calls to respect 15 RPM free-tier limit,
        # but skip the sleep after the final section.
        if idx < len(section_builders) - 1:
            logger.debug("[ReportSynthesis] Sleeping 4s between Gemini calls")
            time.sleep(4)

    overall_confidence = _rollup_confidence(sections)

    generated_at = datetime.now(timezone.utc).isoformat()

    report: dict = {
        "ticker": ticker,
        "generated_at": generated_at,
        "sections": sections,
        "overall_confidence": overall_confidence,
        "disclaimer": (
            "This report is for educational purposes only and does not constitute "
            "financial advice."
        ),
    }

    elapsed = round(time.monotonic() - t_start, 2)
    logger.info(
        "[ReportSynthesis] Completed in %.2fs for %s (overall_confidence=%s)",
        elapsed, ticker, overall_confidence,
    )

    return {
        "report": report,
        "metadata": {
            "agent_latencies": {"report_synthesis": elapsed},
        },
    }
